/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Vika
 */
public class ShopPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShopPanel
     */
    public ShopPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelShopkeeper = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaShop = new javax.swing.JTextArea();
        bBuyShop = new javax.swing.JButton();
        jLabelInventory = new javax.swing.JLabel();
        jLabelShop = new javax.swing.JLabel();
        tbShopD2 = new javax.swing.JToggleButton();
        tbShopA1 = new javax.swing.JToggleButton();
        tbShopA2 = new javax.swing.JToggleButton();
        tbShopA3 = new javax.swing.JToggleButton();
        tbShopB1 = new javax.swing.JToggleButton();
        tbShopB2 = new javax.swing.JToggleButton();
        tbShopB3 = new javax.swing.JToggleButton();
        tbShopB4 = new javax.swing.JToggleButton();
        tbShopB5 = new javax.swing.JToggleButton();
        tbShopC1 = new javax.swing.JToggleButton();
        tbShopC2 = new javax.swing.JToggleButton();
        tbShopD1 = new javax.swing.JToggleButton();
        bToLauncher = new javax.swing.JButton();
        jLabelGlassesShop = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bToSkill = new javax.swing.JButton();
        bToGame = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tbInventoryA1 = new javax.swing.JToggleButton();
        tbInventoryA2 = new javax.swing.JToggleButton();
        tbInventoryA3 = new javax.swing.JToggleButton();
        tbInventoryB1 = new javax.swing.JToggleButton();
        tbInventoryB2 = new javax.swing.JToggleButton();
        tbInventoryB3 = new javax.swing.JToggleButton();
        tbInventoryB4 = new javax.swing.JToggleButton();
        tbInventoryB5 = new javax.swing.JToggleButton();
        tbInventoryC1 = new javax.swing.JToggleButton();
        tbInventoryC2 = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        hierWarPlatzÜbrig = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(650, 750));
        setMinimumSize(new java.awt.Dimension(650, 750));
        setPreferredSize(new java.awt.Dimension(650, 750));
        setLayout(null);

        jLabelShopkeeper.setBackground(new java.awt.Color(204, 255, 204));
        jLabelShopkeeper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proj_1/ScreenLaun/Screen.png"))); // NOI18N
        jLabelShopkeeper.setText("jLabel1");
        add(jLabelShopkeeper);
        jLabelShopkeeper.setBounds(170, 70, 310, 370);

        jTextAreaShop.setColumns(20);
        jTextAreaShop.setRows(5);
        jScrollPane1.setViewportView(jTextAreaShop);

        add(jScrollPane1);
        jScrollPane1.setBounds(170, 490, 310, 160);

        bBuyShop.setText("Kaufen");
        add(bBuyShop);
        bBuyShop.setBounds(170, 660, 310, 80);

        jLabelInventory.setText("Inventar");
        add(jLabelInventory);
        jLabelInventory.setBounds(490, 10, 150, 40);

        jLabelShop.setText("Shop");
        add(jLabelShop);
        jLabelShop.setBounds(10, 10, 150, 40);

        tbShopD2.setText("jToggleButton1");
        add(tbShopD2);
        tbShopD2.setBounds(20, 620, 105, 30);

        tbShopA1.setText("jToggleButton1");
        add(tbShopA1);
        tbShopA1.setBounds(20, 90, 105, 30);

        tbShopA2.setText("jToggleButton1");
        add(tbShopA2);
        tbShopA2.setBounds(20, 130, 105, 30);

        tbShopA3.setText("jToggleButton1");
        add(tbShopA3);
        tbShopA3.setBounds(20, 170, 105, 30);

        tbShopB1.setText("jToggleButton1");
        add(tbShopB1);
        tbShopB1.setBounds(20, 250, 105, 30);

        tbShopB2.setText("jToggleButton1");
        add(tbShopB2);
        tbShopB2.setBounds(20, 290, 105, 30);

        tbShopB3.setText("jToggleButton1");
        add(tbShopB3);
        tbShopB3.setBounds(20, 330, 105, 30);

        tbShopB4.setText("jToggleButton1");
        add(tbShopB4);
        tbShopB4.setBounds(20, 370, 105, 30);

        tbShopB5.setText("jToggleButton1");
        add(tbShopB5);
        tbShopB5.setBounds(20, 410, 105, 30);

        tbShopC1.setText("jToggleButton1");
        add(tbShopC1);
        tbShopC1.setBounds(20, 460, 105, 30);

        tbShopC2.setText("jToggleButton1");
        add(tbShopC2);
        tbShopC2.setBounds(20, 500, 105, 30);

        tbShopD1.setText("jToggleButton1");
        add(tbShopD1);
        tbShopD1.setBounds(20, 580, 105, 30);

        bToLauncher.setText("Launcher");
        bToLauncher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bToLauncherActionPerformed(evt);
            }
        });
        add(bToLauncher);
        bToLauncher.setBounds(170, 20, 310, 40);

        jLabelGlassesShop.setText("Brillen: 0");
        add(jLabelGlassesShop);
        jLabelGlassesShop.setBounds(170, 450, 310, 30);

        jLabel7.setText("Events");
        add(jLabel7);
        jLabel7.setBounds(20, 560, 100, 14);

        bToSkill.setText("Skillbaum");
        bToSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bToSkillActionPerformed(evt);
            }
        });
        add(bToSkill);
        bToSkill.setBounds(500, 700, 140, 40);

        bToGame.setText("Zurück");
        bToGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bToGameActionPerformed(evt);
            }
        });
        add(bToGame);
        bToGame.setBounds(500, 650, 140, 40);

        bSave.setText("Speichern");
        add(bSave);
        bSave.setBounds(10, 670, 140, 70);

        jLabel8.setText("Ausrüstung");
        add(jLabel8);
        jLabel8.setBounds(20, 70, 100, 14);

        jLabel9.setText("Waffen");
        add(jLabel9);
        jLabel9.setBounds(20, 230, 100, 14);

        tbInventoryA1.setText("jToggleButton1");
        add(tbInventoryA1);
        tbInventoryA1.setBounds(520, 90, 105, 30);

        tbInventoryA2.setText("jToggleButton1");
        add(tbInventoryA2);
        tbInventoryA2.setBounds(520, 130, 105, 30);

        tbInventoryA3.setText("jToggleButton1");
        add(tbInventoryA3);
        tbInventoryA3.setBounds(520, 170, 105, 30);

        tbInventoryB1.setText("jToggleButton1");
        add(tbInventoryB1);
        tbInventoryB1.setBounds(520, 250, 105, 30);

        tbInventoryB2.setText("jToggleButton1");
        add(tbInventoryB2);
        tbInventoryB2.setBounds(520, 290, 105, 30);

        tbInventoryB3.setText("jToggleButton1");
        add(tbInventoryB3);
        tbInventoryB3.setBounds(520, 330, 105, 30);

        tbInventoryB4.setText("jToggleButton1");
        add(tbInventoryB4);
        tbInventoryB4.setBounds(520, 370, 105, 30);

        tbInventoryB5.setText("jToggleButton1");
        add(tbInventoryB5);
        tbInventoryB5.setBounds(520, 410, 105, 30);

        tbInventoryC1.setText("jToggleButton1");
        add(tbInventoryC1);
        tbInventoryC1.setBounds(520, 460, 105, 30);

        tbInventoryC2.setText("jToggleButton1");
        add(tbInventoryC2);
        tbInventoryC2.setBounds(520, 500, 105, 30);

        jLabel10.setText("Ausrüstung");
        add(jLabel10);
        jLabel10.setBounds(520, 70, 100, 14);

        jLabel11.setText("Waffen");
        add(jLabel11);
        jLabel11.setBounds(520, 230, 100, 14);

        hierWarPlatzÜbrig.setText("jLabel5");
        add(hierWarPlatzÜbrig);
        hierWarPlatzÜbrig.setBounds(500, 550, 140, 90);
    }// </editor-fold>//GEN-END:initComponents

    private void bToGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bToGameActionPerformed
 MainGUI.changeCard("game card",MainGUI.clgame,MainGUI.gamecards);        
    }//GEN-LAST:event_bToGameActionPerformed

    private void bToSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bToSkillActionPerformed
 MainGUI.changeCard("skill card",MainGUI.clgame,MainGUI.gamecards);      
    }//GEN-LAST:event_bToSkillActionPerformed

    private void bToLauncherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bToLauncherActionPerformed
              //speichereSpiel(beendeteLevel, brillen, lebendeStreber, getoeteteStreber);
        Launcher l = new Launcher();
        //l.Launcher();
        //TODO: Musik vom Spiel beenden.
        MainGUI.gamescreen.setVisible(false);

        System.out.println("gamescreen wird unsichtbar und anschließend zerstört"
                + "(dispose)");
        MainGUI.gamescreen.dispose();
    }//GEN-LAST:event_bToLauncherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuyShop;
    private javax.swing.JButton bSave;
    private javax.swing.JButton bToGame;
    private javax.swing.JButton bToLauncher;
    private javax.swing.JButton bToSkill;
    private javax.swing.JLabel hierWarPlatzÜbrig;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelGlassesShop;
    private javax.swing.JLabel jLabelInventory;
    private javax.swing.JLabel jLabelShop;
    private javax.swing.JLabel jLabelShopkeeper;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaShop;
    private javax.swing.JToggleButton tbInventoryA1;
    private javax.swing.JToggleButton tbInventoryA2;
    private javax.swing.JToggleButton tbInventoryA3;
    private javax.swing.JToggleButton tbInventoryB1;
    private javax.swing.JToggleButton tbInventoryB2;
    private javax.swing.JToggleButton tbInventoryB3;
    private javax.swing.JToggleButton tbInventoryB4;
    private javax.swing.JToggleButton tbInventoryB5;
    private javax.swing.JToggleButton tbInventoryC1;
    private javax.swing.JToggleButton tbInventoryC2;
    private javax.swing.JToggleButton tbShopA1;
    private javax.swing.JToggleButton tbShopA2;
    private javax.swing.JToggleButton tbShopA3;
    private javax.swing.JToggleButton tbShopB1;
    private javax.swing.JToggleButton tbShopB2;
    private javax.swing.JToggleButton tbShopB3;
    private javax.swing.JToggleButton tbShopB4;
    private javax.swing.JToggleButton tbShopB5;
    private javax.swing.JToggleButton tbShopC1;
    private javax.swing.JToggleButton tbShopC2;
    private javax.swing.JToggleButton tbShopD1;
    private javax.swing.JToggleButton tbShopD2;
    // End of variables declaration//GEN-END:variables
}
