/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.KeyEvent;

/**
 *
 * @author Vika
 */
public class SkillPanel extends javax.swing.JPanel implements Panel {

    /**
     * Creates new form SkillPanel
     */
    public SkillPanel() {
        initComponents();
        shortKeys();
    }

    private void shortKeys() {

        WindowProperties.setShortKeys(bToShopSkill, "shop card", KeyEvent.VK_N);
        WindowProperties.setShortKeys(bToGameSkill, "game card", KeyEvent.VK_B);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSkill = new javax.swing.JTextArea();
        jLabelSensei = new javax.swing.JLabel();
        jLabelEXPSkill = new javax.swing.JLabel();
        jLabelGlassesSkill = new javax.swing.JLabel();
        bBuyGlassesSkill = new javax.swing.JButton();
        jLabelSkilltree = new javax.swing.JLabel();
        tbSkillD2 = new javax.swing.JToggleButton();
        tbSkillB8 = new javax.swing.JToggleButton();
        tbSkillB5 = new javax.swing.JToggleButton();
        tbSkillB1 = new javax.swing.JToggleButton();
        tbSkillB2 = new javax.swing.JToggleButton();
        tbSkillB3 = new javax.swing.JToggleButton();
        tbSkillB6 = new javax.swing.JToggleButton();
        tbSkillB7 = new javax.swing.JToggleButton();
        tbSkillB9 = new javax.swing.JToggleButton();
        tbSkillB10 = new javax.swing.JToggleButton();
        tbSkillB11 = new javax.swing.JToggleButton();
        tbSkillB4 = new javax.swing.JToggleButton();
        tbSkillC4 = new javax.swing.JToggleButton();
        tbSkillC1 = new javax.swing.JToggleButton();
        tbSkillC5 = new javax.swing.JToggleButton();
        tbSkillC2 = new javax.swing.JToggleButton();
        tbSkillC6 = new javax.swing.JToggleButton();
        tbSkillC3 = new javax.swing.JToggleButton();
        tbSkillC10 = new javax.swing.JToggleButton();
        tbSkillC7 = new javax.swing.JToggleButton();
        tbSkillC11 = new javax.swing.JToggleButton();
        tbSkillC8 = new javax.swing.JToggleButton();
        tbSkillC12 = new javax.swing.JToggleButton();
        tbSkillC9 = new javax.swing.JToggleButton();
        tbSkillF = new javax.swing.JToggleButton();
        tbSkillD1 = new javax.swing.JToggleButton();
        tbSkillE1 = new javax.swing.JToggleButton();
        tbSkillE2 = new javax.swing.JToggleButton();
        tbSkillE3 = new javax.swing.JToggleButton();
        tbSkillE4 = new javax.swing.JToggleButton();
        tbSkillE5 = new javax.swing.JToggleButton();
        tbSkillE6 = new javax.swing.JToggleButton();
        tbSkillE7 = new javax.swing.JToggleButton();
        tbSkillE8 = new javax.swing.JToggleButton();
        tbSkillA1 = new javax.swing.JToggleButton();
        bToShopSkill = new javax.swing.JButton();
        bToGameSkill = new javax.swing.JButton();
        bBuyEXPSkill = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(650, 750));
        setMinimumSize(new java.awt.Dimension(650, 750));
        setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaSkill.setEditable(false);
        jTextAreaSkill.setColumns(20);
        jTextAreaSkill.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSkill);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 400, 220, 340);

        jLabelSensei.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScreenLaun/MenuBG.jpg"))); // NOI18N
        jLabelSensei.setText("jLabel1");
        add(jLabelSensei);
        jLabelSensei.setBounds(10, 10, 220, 300);

        jLabelEXPSkill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEXPSkill.setText("Erfahrung: 0");
        add(jLabelEXPSkill);
        jLabelEXPSkill.setBounds(10, 314, 100, 20);

        jLabelGlassesSkill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelGlassesSkill.setText("Brillen: 0");
        add(jLabelGlassesSkill);
        jLabelGlassesSkill.setBounds(130, 314, 100, 20);

        bBuyGlassesSkill.setBackground(new java.awt.Color(0, 0, 0));
        bBuyGlassesSkill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bBuyGlassesSkill.setForeground(new java.awt.Color(255, 255, 255));
        bBuyGlassesSkill.setText("Kaufen");
        add(bBuyGlassesSkill);
        bBuyGlassesSkill.setBounds(130, 340, 100, 50);

        jLabelSkilltree.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelSkilltree.setText("             Skillbaum");
        add(jLabelSkilltree);
        jLabelSkilltree.setBounds(290, 10, 300, 40);

        buttonGroup1.add(tbSkillD2);
        tbSkillD2.setText("jToggleButton1");
        add(tbSkillD2);
        tbSkillD2.setBounds(490, 390, 120, 40);

        buttonGroup1.add(tbSkillB8);
        tbSkillB8.setText("jToggleButton2");
        add(tbSkillB8);
        tbSkillB8.setBounds(510, 110, 80, 30);

        buttonGroup1.add(tbSkillB5);
        tbSkillB5.setText("jToggleButton2");
        add(tbSkillB5);
        tbSkillB5.setBounds(400, 110, 80, 30);

        buttonGroup1.add(tbSkillB1);
        tbSkillB1.setText("jToggleButton2");
        add(tbSkillB1);
        tbSkillB1.setBounds(290, 110, 80, 30);

        buttonGroup1.add(tbSkillB2);
        tbSkillB2.setText("jToggleButton2");
        add(tbSkillB2);
        tbSkillB2.setBounds(290, 150, 80, 30);

        buttonGroup1.add(tbSkillB3);
        tbSkillB3.setText("jToggleButton2");
        add(tbSkillB3);
        tbSkillB3.setBounds(290, 190, 80, 30);

        buttonGroup1.add(tbSkillB6);
        tbSkillB6.setText("jToggleButton2");
        add(tbSkillB6);
        tbSkillB6.setBounds(400, 150, 80, 30);

        buttonGroup1.add(tbSkillB7);
        tbSkillB7.setText("jToggleButton2");
        add(tbSkillB7);
        tbSkillB7.setBounds(400, 190, 80, 30);

        buttonGroup1.add(tbSkillB9);
        tbSkillB9.setText("jToggleButton2");
        add(tbSkillB9);
        tbSkillB9.setBounds(510, 150, 80, 30);

        buttonGroup1.add(tbSkillB10);
        tbSkillB10.setText("jToggleButton2");
        add(tbSkillB10);
        tbSkillB10.setBounds(510, 190, 80, 30);

        buttonGroup1.add(tbSkillB11);
        tbSkillB11.setText("jToggleButton2");
        add(tbSkillB11);
        tbSkillB11.setBounds(510, 230, 80, 30);

        buttonGroup1.add(tbSkillB4);
        tbSkillB4.setText("jToggleButton2");
        add(tbSkillB4);
        tbSkillB4.setBounds(290, 230, 80, 30);

        buttonGroup1.add(tbSkillC4);
        tbSkillC4.setText("jToggleButton2");
        add(tbSkillC4);
        tbSkillC4.setBounds(340, 280, 60, 23);

        buttonGroup1.add(tbSkillC1);
        tbSkillC1.setText("jToggleButton2");
        add(tbSkillC1);
        tbSkillC1.setBounds(260, 280, 60, 23);

        buttonGroup1.add(tbSkillC5);
        tbSkillC5.setText("jToggleButton2");
        add(tbSkillC5);
        tbSkillC5.setBounds(340, 310, 60, 23);

        buttonGroup1.add(tbSkillC2);
        tbSkillC2.setText("jToggleButton2");
        add(tbSkillC2);
        tbSkillC2.setBounds(260, 310, 60, 23);

        buttonGroup1.add(tbSkillC6);
        tbSkillC6.setText("jToggleButton2");
        add(tbSkillC6);
        tbSkillC6.setBounds(340, 340, 60, 23);

        buttonGroup1.add(tbSkillC3);
        tbSkillC3.setText("jToggleButton2");
        add(tbSkillC3);
        tbSkillC3.setBounds(260, 340, 60, 23);

        buttonGroup1.add(tbSkillC10);
        tbSkillC10.setText("jToggleButton2");
        add(tbSkillC10);
        tbSkillC10.setBounds(560, 280, 60, 23);

        buttonGroup1.add(tbSkillC7);
        tbSkillC7.setText("jToggleButton2");
        add(tbSkillC7);
        tbSkillC7.setBounds(480, 280, 60, 23);

        buttonGroup1.add(tbSkillC11);
        tbSkillC11.setText("jToggleButton2");
        add(tbSkillC11);
        tbSkillC11.setBounds(560, 310, 60, 23);

        buttonGroup1.add(tbSkillC8);
        tbSkillC8.setText("jToggleButton2");
        add(tbSkillC8);
        tbSkillC8.setBounds(480, 310, 60, 23);

        buttonGroup1.add(tbSkillC12);
        tbSkillC12.setText("jToggleButton2");
        add(tbSkillC12);
        tbSkillC12.setBounds(560, 340, 60, 23);

        buttonGroup1.add(tbSkillC9);
        tbSkillC9.setText("jToggleButton2");
        add(tbSkillC9);
        tbSkillC9.setBounds(480, 340, 60, 23);

        buttonGroup1.add(tbSkillF);
        tbSkillF.setText("jToggleButton1");
        add(tbSkillF);
        tbSkillF.setBounds(370, 620, 140, 50);

        buttonGroup1.add(tbSkillD1);
        tbSkillD1.setText("jToggleButton1");
        add(tbSkillD1);
        tbSkillD1.setBounds(270, 390, 120, 40);

        buttonGroup1.add(tbSkillE1);
        tbSkillE1.setText("jToggleButton2");
        add(tbSkillE1);
        tbSkillE1.setBounds(290, 450, 80, 30);

        buttonGroup1.add(tbSkillE2);
        tbSkillE2.setText("jToggleButton2");
        add(tbSkillE2);
        tbSkillE2.setBounds(290, 490, 80, 30);

        buttonGroup1.add(tbSkillE3);
        tbSkillE3.setText("jToggleButton2");
        add(tbSkillE3);
        tbSkillE3.setBounds(290, 530, 80, 30);

        buttonGroup1.add(tbSkillE4);
        tbSkillE4.setText("jToggleButton2");
        add(tbSkillE4);
        tbSkillE4.setBounds(290, 570, 80, 30);

        buttonGroup1.add(tbSkillE5);
        tbSkillE5.setText("jToggleButton2");
        add(tbSkillE5);
        tbSkillE5.setBounds(510, 450, 80, 30);

        buttonGroup1.add(tbSkillE6);
        tbSkillE6.setText("jToggleButton2");
        add(tbSkillE6);
        tbSkillE6.setBounds(510, 490, 80, 30);

        buttonGroup1.add(tbSkillE7);
        tbSkillE7.setText("jToggleButton2");
        add(tbSkillE7);
        tbSkillE7.setBounds(510, 530, 80, 30);

        buttonGroup1.add(tbSkillE8);
        tbSkillE8.setText("jToggleButton2");
        add(tbSkillE8);
        tbSkillE8.setBounds(510, 570, 80, 30);

        buttonGroup1.add(tbSkillA1);
        tbSkillA1.setText("jToggleButton1");
        add(tbSkillA1);
        tbSkillA1.setBounds(380, 60, 120, 40);

        bToShopSkill.setBackground(new java.awt.Color(0, 0, 0));
        bToShopSkill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bToShopSkill.setForeground(new java.awt.Color(255, 255, 255));
        bToShopSkill.setText("Shop");
        bToShopSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bToShopSkillActionPerformed(evt);
            }
        });
        add(bToShopSkill);
        bToShopSkill.setBounds(240, 690, 120, 50);

        bToGameSkill.setBackground(new java.awt.Color(0, 0, 0));
        bToGameSkill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bToGameSkill.setForeground(new java.awt.Color(255, 255, 255));
        bToGameSkill.setText("Zurück");
        bToGameSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bToGameSkillActionPerformed(evt);
            }
        });
        add(bToGameSkill);
        bToGameSkill.setBounds(520, 690, 120, 50);

        bBuyEXPSkill.setBackground(new java.awt.Color(0, 0, 0));
        bBuyEXPSkill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bBuyEXPSkill.setForeground(new java.awt.Color(255, 255, 255));
        bBuyEXPSkill.setText("Kaufen");
        add(bBuyEXPSkill);
        bBuyEXPSkill.setBounds(10, 340, 100, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void bToGameSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bToGameSkillActionPerformed
        MainGUI.getAktMainGUI().changeCard("game card");
    }//GEN-LAST:event_bToGameSkillActionPerformed

    private void bToShopSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bToShopSkillActionPerformed
        MainGUI.getAktMainGUI().changeCard("shop card");
    }//GEN-LAST:event_bToShopSkillActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuyEXPSkill;
    private javax.swing.JButton bBuyGlassesSkill;
    private javax.swing.JButton bToGameSkill;
    private javax.swing.JButton bToShopSkill;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabelEXPSkill;
    private javax.swing.JLabel jLabelGlassesSkill;
    private javax.swing.JLabel jLabelSensei;
    private javax.swing.JLabel jLabelSkilltree;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSkill;
    private javax.swing.JToggleButton tbSkillA1;
    private javax.swing.JToggleButton tbSkillB1;
    private javax.swing.JToggleButton tbSkillB10;
    private javax.swing.JToggleButton tbSkillB11;
    private javax.swing.JToggleButton tbSkillB2;
    private javax.swing.JToggleButton tbSkillB3;
    private javax.swing.JToggleButton tbSkillB4;
    private javax.swing.JToggleButton tbSkillB5;
    private javax.swing.JToggleButton tbSkillB6;
    private javax.swing.JToggleButton tbSkillB7;
    private javax.swing.JToggleButton tbSkillB8;
    private javax.swing.JToggleButton tbSkillB9;
    private javax.swing.JToggleButton tbSkillC1;
    private javax.swing.JToggleButton tbSkillC10;
    private javax.swing.JToggleButton tbSkillC11;
    private javax.swing.JToggleButton tbSkillC12;
    private javax.swing.JToggleButton tbSkillC2;
    private javax.swing.JToggleButton tbSkillC3;
    private javax.swing.JToggleButton tbSkillC4;
    private javax.swing.JToggleButton tbSkillC5;
    private javax.swing.JToggleButton tbSkillC6;
    private javax.swing.JToggleButton tbSkillC7;
    private javax.swing.JToggleButton tbSkillC8;
    private javax.swing.JToggleButton tbSkillC9;
    private javax.swing.JToggleButton tbSkillD1;
    private javax.swing.JToggleButton tbSkillD2;
    private javax.swing.JToggleButton tbSkillE1;
    private javax.swing.JToggleButton tbSkillE2;
    private javax.swing.JToggleButton tbSkillE3;
    private javax.swing.JToggleButton tbSkillE4;
    private javax.swing.JToggleButton tbSkillE5;
    private javax.swing.JToggleButton tbSkillE6;
    private javax.swing.JToggleButton tbSkillE7;
    private javax.swing.JToggleButton tbSkillE8;
    private javax.swing.JToggleButton tbSkillF;
    // End of variables declaration//GEN-END:variables

    public void setGlasses(int br) {
        jLabelGlassesSkill.setText("Brillen: " + br);
    }

    public void setEXP(int exp) {
        jLabelEXPSkill.setText("Brillen: " + exp);
    }

    public void setLabels(int br, int exp) {
        setGlasses(br);
        setEXP(exp);
    }

    @Override
    public void disableButtons() {
        
    }

    @Override
    public void switchTo() {
       
    }

    @Override
    public void switchFrom() {
        
    }
}
